services:
  flapamamaku-backend:
    image: ghcr.io/kublae1/flapamamaku-backend:latest
    pull_policy: always
    container_name: flapamamaku-backend
    restart: unless-stopped
    ports:
      - "8087:8000"
    environment:
      FLAPAMAMAKU_DB: /data/flapamamaku.db
    volumes:
      - flapamamaku-data:/data

volumes:
  flapamamaku-data:
